CREATE TABLE QUESTIONS (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    tag_id VARCHAR(255) NOT NULL DEFAULT '53dc6a4e-2aa9-414a-b95e-a0e7d6156998',
    user_id VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    views INT NOT NULL DEFAULT 0,
    is_deleted BIT DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (user_id) REFERENCES USERDB(id),
    FOREIGN KEY (tag_id) REFERENCES TAGS(id)
);