CREATE TABLE ANSWER_VOTE (
    id VARCHAR(255) PRIMARY KEY,
    upvote BIT NOT NULL DEFAULT 0,
    downvote BIT NOT NULL DEFAULT 0,
    answer_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    votes INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (answer_id) REFERENCES ANSWERS(id),
    FOREIGN KEY (user_id) REFERENCES USERDB(id) ON DELETE CASCADE
);
