CREATE TABLE ANSWER_VOTE
(
    id VARCHAR ( 255 ) PRIMARY KEY ,
    vote INT NOT NULL ,
    answer_id VARCHAR ( 255 ) NOT NULL ,
	created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (answer_id) REFERENCES ANSWERS(id),

);