CREATE TABLE QUESTIONS (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    tags VARCHAR(255) NOT NULL,
    views INT NOT NULL DEFAULT 0,
    is_deleted BIT DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (user_id) REFERENCES USERDB(id),
);

