CREATE TABLE ANSWER_VOTE
(
    id VARCHAR ( 255 ) PRIMARY KEY ,
    vote INT NOT NULL ,
    user_id VARCHAR ( 100 ) NOT NULL ,
    answer_id VARCHAR ( 255 ) NOT NULL ,
	created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (user_id) REFERENCES USERDB(id),
    FOREIGN KEY (answer_id) REFERENCES ANSWERS(id),
    CONSTRAINT FK_answer_votes_user_id_users_id FOREIGN KEY (user_id) REFERENCES USERDB(id) ON DELETE CASCADE,

);